\documentclass{article}

\begin{document}
\textbf{RICHARD MATHEW QUIZ 7\\}
<<echo=FALSE, warning=FALSE>>=
#install.packages("rvest", repos="http://cran.us.r-project.org")
#library("rvest")

tablenumber <- 2;
address <- rvest::html("http://en.wikipedia.org/wiki/Ebola_virus_epidemic_in_West_Africa")
ebola <- rvest::html_table(rvest::html_nodes(address, "table")[[tablenumber]])
#names(ebola)
sumofcase <- ebola[10,"Cases"]
sumofdeath <- ebola[10,"Deaths"]


#USA ebola cases and deaths
usCases <- ebola[6,"Cases"]
usDeaths <- ebola[6,"Deaths"]
@

The World Health Organization (WHO) and respective governments have reported a total of \(\Sexpr{sumofcase}\) suspected cases and \(\Sexpr{sumofdeath}\) deaths, though the WHO believes that this substantially understates the magnitude of the outbreak. In the United States there has been \(\Sexpr{usCases}\) reported cases and \(\Sexpr{usDeaths}\) deaths

\end{document}